config/routes.rb
Sblog::Application.routes.draw do

  devise_for :users

  root :to => "posts#index"

  resources :posts do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :body, :presence => true, :length => {:minimum => 10, :maximum => 100}

  default_scope :order => 'comments.created_at DESC'
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :content

  validates :title, :presence => true, :length => {:minimum => 20, :maximum => 100}
  validates :content, :presence => true, :length => {:minimum => 100, :maximum => 2000}

  belongs_to :user
  has_many :comments

  default_scope :order => 'posts.created_at DESC'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :posts
  has_many :comments, :through => :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @user = User.find(current_user)

    @comment = @post.comments.create(params[:comment])
    @comment.user_id = @user.id
    @comment.save
  #  redirect_to post_path(@post)

    respond_to do |format|
      format.html  {redirect_to post_path(@post)}# show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html  # show.html.erb
      format.xml  { render :xml => @post }
      format.js
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  def new
    @post = Post.new

    respond_to do |format|
      format.html  # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  def create
    @post = Post.new(params[:post])
    @user = User.find(current_user)
    @post.user_id = @user.id
    @post.likes = 0

    respond_to do |format|
      if @post.save
        format.html  { redirect_to(@post,
                      :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post,
                      :status => :created, :location => @post }
  #      format.js
      else
        format.html  { render :action => "new" }
        format.xml  { render :xml => @post.errors,
                      :status => :unprocessable_entity }
      end
    end
  end

  def show
    @post = Post.find(params[:id])
    @post.likes = @post.likes + 1
    @post.save

    respond_to do |format|
      format.html  # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html  { redirect_to(@post,
                      :notice => 'Post was successfully updated.') }
        format.xml  { render :xml => {}, :status => :ok }
      else
        format.html  { render :action => "edit" }
        format.xml  { render :xml => @post.errors,
                      :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html  # show.html.erb
      format.xml  { render :xml => @post }
      format.js
    end
  end

 # def like
 #   @post = Post.find(param[:id])
 #   @post.likes = @post.likes + 1
 #   @post.save
 # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="field">
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit Comment' %>
  </div>
<% end %>

app/views/comments/destroy.js.erb
$(document).ready(function() {
$("p.comment").bind("ajax:success", function() {
$(this).closest("p").fadeOut();
});
});

app/views/layouts/_footer.html.erb
<footer>
  <nav>
    <ul>
      <li><%= link_to "Home", '/home' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<%= javascript_include_tag 'rails' %>
<%= javascript_include_tag :defaults %>
    <header  class="body">
        <% logo = image_tag("logo.png", :alt => "SBlog!", :class => "round") %>
        <h1><%= link_to logo, posts_path %></h1>
        <nav>
          <ul>
            <li><%= link_to "Home", posts_path %></li>
            <% if user_signed_in? %>
              <li>Welcome, <%= link_to(current_user.email, edit_user_registration_path) %>
                <li><%= link_to 'New Post', new_post_path %></li>
              <li><%= link_to('Sign out', destroy_user_session_path, :method => :delete) %></li>
              </li>
            <% else %>
              <li>
              <%= link_to('Sign in', new_user_session_path)  %>
              <li><%= link_to('Sign up', new_user_registration_path) %></li>
              </li>
            <% end %>
          </ul>
        </nav>
      </header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sblog!</title>
  <%= javascript_include_tag 'jquery' %>
  <%= javascript_include_tag 'jquery-ui' %>
  <%= javascript_include_tag 'rails' %>
  <%= csrf_meta_tag %>
  <%= render 'layouts/stylesheets' %>
</head>
<body>

<div class="container">
    <%= render 'layouts/header' %>
  <section>
    <%= yield %>
   </section>
</div>

</body>
</html>

app/views/posts/_commentdisp.html.erb
<% @post.comments.each do |comment| %>
    <% if(comment.body.nil? == false) %>
         <p class="comment">
            <span class="timestamp">
                Posted <%= time_ago_in_words(comment.created_at) %> ago.
            </span><br>
            <span class="comment"><%= comment.body %></span>
           <% @user = current_user
              if(user_signed_in? && @user.id == comment.user_id) %>
            <%= link_to 'Delete Comment', [comment.post, comment],
               :confirm => 'Are you sure?',
               :method => :delete, :remote => true %>
               <% end %>
         </p>
    <% end %>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
      <div id="errorExplanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <br><%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit Post' %>
  </div>
<% end %>

app/views/posts/_topfeed.html.erb
<div class="post">
<h1>Popular News</h1>
  <% @posts = @posts.sort_by(&:likes).reverse %>
<% @posts.each do |post| %>
    <span class="topfeed"><%= link_to post.title, post %></span>
<% end %>
</div>

app/views/posts/destroy.js.erb
$(document).ready(function() {
$("td.post").bind("ajax:success", function() {
$(this).closest("tr").fadeOut();
});
});

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>
<br>
<%= link_to 'View Post', @post %> |
<%= link_to 'Back to Sblog! Home', posts_path %>

app/views/posts/index.html.erb
<h1>News Feed</h1>

<div class="feed">
<table>

<% @posts.each do |post| %>

 <tr>
  <td class="post">
    <span class="title"><%= link_to post.title, post %></span><br>
    <span class="content"><%=h truncate(post.content, :length => 500) %></span><br>
    <span class="timestamp">
      <% @user = User.find(post.user_id) %>
      Posted by <%= @user.email %> <%= time_ago_in_words(post.created_at) %> ago.
    </span>
    <% if user_signed_in? and current_user == @user %>
      <span><%= link_to 'Edit Post', edit_post_path(post) %></span>
    <span><%= link_to 'Delete Post', post, :confirm => 'Are you sure?', :method => :delete, :remote => true, :class => 'post' %></span>
    <% end %>
  </td>
</tr>
<% end %>
</table>
</div>
<%= render 'topfeed' %>

app/views/posts/new.html.erb
<h1>Create new post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="feed">
<p>
  <h2><%= @post.title %></h2>
      <span class="timestamp">
      <% @user = User.find(@post.user_id) %>
      Posted by <%= @user.email %> <%= time_ago_in_words(@post.created_at) %> ago.
    </span>
  <% if user_signed_in? and current_user == @user %>
  <%= link_to 'Edit Post', edit_post_path(@post) %>
  <% end %>
</p>

<p>
  <%= @post.content %>
</p>
<h2>Add New Comment</h2>
  <% if user_signed_in? %>
<%= render "comments/form" %><br>
  <% else %>
   Please <%= link_to('Sign in', new_user_session_path)  %> to post a comment.
      <% end %>  <br><br><br>
<h2>Comments</h2>
<%= render "commentdisp" %>
</div>